### ISSUE TITLE
Failed to start Lisp process

### ISSUE THREAD

**Issue by Limits0x** [s-clerc/slyblime#11]
Hi, I have installed SublimeRepl and slyblime on Sublime Text 4 (build 4101) on Windows 10.
I also ran `Sly: Upgrade SublimeREPL to work with Sly`.
I set the `Inferior lisp command` to `sbcl --load` as I am using `sbcl`.
Then, I tried running `Sly: Start and connect to an inferior Lisp instance`.
But, I got an error:
![img](https://user-images.githubusercontent.com/44343120/113991459-19b54000-9870-11eb-9bf1-e16186f9b1ae.png)
How do I fix this ?

**Comment by s-clerc** [comment]
Hello,

Thank you for using Slyblime, I don't own a Windows computer so I've not been able to test it, but I think it should work fine.

Firstly, you probably want to set the command to just `sbcl` and not `sbcl --load` as it is possible that `--load` is causing SBCL to not start up correctly.

Secondly, another problem I have identified is that the default timeout is too low for some computers:
```json
"inferior_lisp_process": {
    "command": ["lisp"],
    "autoclose": true,
    "loading_time": 2,
    "setup_time": 1
  }
```
By default `loading_time` and `setup_time` are two and one seconds respectively; however, on some computers the lisp process may take longer than that to load and setup. Try setting both to `4` seconds and see what happens.
(I intend to rectify these issues in the next release, but I need to prepare for exams unfortunately).

**Comment by Limits0x** [comment]
I tried setting them:
![image](https://user-images.githubusercontent.com/44343120/114004656-81718800-987c-11eb-9744-6f700662b860.png)
But, I still get the same error.
The problem might be with the chosen port. Is it possible to change it ?

**Comment by Limits0x** [comment]
I ran the `Sly: Start and connect to an inferior Lisp instance` command and opened task manager to see what was happenning in the background. This is the result:
![image](https://user-images.githubusercontent.com/44343120/114011896-5cccde80-9883-11eb-92d3-137e7f54a26c.png)
Looks like `sbcl` is being called.

**Comment by Limits0x** [comment]
I was able to get it to work by manually starting the server using `sbcl` and `slynk`.

**Comment by daninus14** [comment]
I had the same issue and this fixed it for me. Btw, how are you passing the timeout variables to sbcl? I have the issue with other programs as well and this would be very useful... Thanks!

**Comment by daninus14** [comment]
> I had the same issue and this fixed it for me. Btw, how are you passing the timeout variables to sbcl? I have the issue with other programs as well and this would be very useful... Thanks!

I saw the code, it's just sleeping the thread, not passing anything actual to sbcl... Thanks anyway for slyblime! :D
